from ghostos.contracts.assets import ImageAssets, AudioAssets
from ghostos.framework.assets.workspace_image_provider import WorkspaceImageAssetsProvider
from ghostos.framework.assets.workspace_audio_provider import WorkspaceAudioAssetsProvider
